### ISSUE TITLE
web.phpでエラーがでている件

### ISSUE THREAD

**Issue by gp-nakai** [gp1000-dev/gp-attendance#115]
web.phpでエラーがでている件で、
vscodeの型チェックに引っかかってることがわかりました。
なので
use Illuminate\Support\Facades\Auth; を追加してみてはいかがでしょうか。

**Comment by gp-yamada** [comment]
use Illuminate\Support\Facades\Auth; 
は追加しないことにします。

- VSCode上でエラー判定されるだけであり、動作上はuseが無くても問題はないこと。
- VSCode上のエラー判定は停止することができること。参照： https://www.searchlight8.com/vscode-laravel-code-error/

個人の動作環境の問題なので追記しないことにし、このIssueはCloseしようと思います。

**Comment by gp-yamada** [comment]
しばらくuseしない方向で様子を見ます。
VSCodeで未宣言エラーが出ますが、そのまま無視するか、設定変更で回避してください。
