### ISSUE TITLE
ユーザーパスワード変更画面

### ISSUE THREAD

**Issue by gp-yamada** [gp1000-dev/gp-attendance#29]
- [ ] URL: /user/password でパスワード変更画面表示
    - [ ] UserControllerにpassword()メソッド追加
    - [ ] View: user/password.blade.php
    - [ ] 「現在のパスワード」「新しいパスワード」「新しいパスワード（確認）」の入力欄
    - [ ] 「変更する」ボタン（動作はしなくていい）

**Comment by gp-sato** [comment]
了解です。

**Comment by gp-yamada** [comment]
訂正
誤）users/password.blade.php
正）user/password.blade.php
失礼しました💦
