### ISSUE TITLE
メニューに「このシステムについて」表示

### ISSUE THREAD

**Issue by gp-yamada** [gp1000-dev/gp-attendance#32]
- [ ] ヘッダーメニューに「このシステムについて」表示
    - [ ] 「GP勤怠管理システム」の右隣（左寄せ）
    - [ ] /about へのリンク

**Comment by gp-yamada** [comment]
- [ ] ヘッダーメニューに「このシステムについて」表示
    - [ ] 「GP勤怠管理システム」の右隣（左寄せ）
    - [ ] /about へのリンク

**Comment by gp-yamada** [comment]
@gp-nakai お願いします。

**Comment by gp-nakai** [comment]
resouces/views/layouts/app.blade.php が対象のファイルの様ですが
ここに書いても良いですか？
またサイズなどの指定はありますでしょうか？

**Comment by gp-yamada** [comment]
> resouces/views/layouts/app.blade.php が対象のファイルの様ですが
> ここに書いても良いですか？
はい、このファイルです。

> またサイズなどの指定はありますでしょうか？
右端の「新規登録」等の文字と同じサイズにしてください。
