### ISSUE TITLE
ダッシュボードに各種リンク

### ISSUE THREAD

**Issue by gp-yamada** [gp1000-dev/gp-attendance#8]
ダッシュボード（dashboard.blade.php）に

- [ ] ログイン画面（/login）へのリンク
- [ ] 「新規ユーザー登録はこちら」としてユーザー登録画面（/register）へのリンク
- [ ] GIFT PLACE ホームページ（https://gp1000.jp ）へのリンク（別ウィンドウで開く）

**Comment by eguchi2404** [comment]
@gp-yamada 
上記のissueは about.blade.php への指示という認識で合っているでしょうか？

**Comment by eguchi2404** [comment]
@gp-yamada 
上記のissueは about.blade.php への指示であっているでしょうか？
また、ヘッダーに上記の内容は実装されているので section('content') 内に練習として実装するものと考えていますがお間違えないでしょうか。

**Comment by gp-yamada** [comment]
＠eguchi-gp1000
タイトルにもある通り、ダッシュボード（dashboard.blade.php）に記述します。
section等の切り分けは既にできているので、コンテンツを書くだけです。
